import { h, api, toast, fmt, state, copy, composer, DOW } from './lib.js';

const acct = () => state.account;
const shieldTag = (s) => h('span', { class: 'tag ' + (s.score >= 60 ? 'failed' : s.score >= 35 ? 'draft' : 'posted') }, `${s.label} ${s.score}`);
const usernameTool = (label, path, render, extra = []) => {
  const u = h('input', { placeholder: '@username', style: 'max-width:240px' }); const out = h('div', { style: 'margin-top:12px' });
  const go = async (e) => { e?.target && (e.target.disabled = true); out.textContent = 'Working…'; try { out.replaceChildren(await render(await api(`${path}${path.includes('?') ? '&' : '?'}account=${acct()}&username=${encodeURIComponent(u.value.replace(/^@/, ''))}`), u.value.replace(/^@/, ''))); } catch (x) { out.replaceChildren(h('span', { style: 'color:var(--bad)' }, x.message)); } e?.target && (e.target.disabled = false); };
  return h('div', {}, h('div', { class: 'row' }, u, ...extra, h('button', { onclick: go }, label)), out);
};
const meter = (pct) => h('div', { class: 'meter' }, h('i', { style: `width:${Math.max(0, Math.min(100, pct))}%` }));

/* Unicode font styles (12) */
const RANGES = { 'Bold': [0x1d5d4, 0x1d5ee, 0x1d7ec], 'Italic': [0x1d608, 0x1d622], 'Bold italic': [0x1d63c, 0x1d656], 'Serif bold': [0x1d400, 0x1d41a, 0x1d7ce], 'Serif italic': [0x1d434, 0x1d44e], 'Script': [0x1d4d0, 0x1d4ea], 'Gothic': [0x1d56c, 0x1d586], 'Double-struck': [0x1d538, 0x1d552, 0x1d7d8], 'Monospace': [0x1d670, 0x1d68a, 0x1d7f6], 'Sans': [0x1d5a0, 0x1d5ba, 0x1d7e2] };
const mapChars = (t, [u, l, d]) => [...t].map((c) => { const k = c.codePointAt(0); return k >= 65 && k <= 90 ? String.fromCodePoint(u + k - 65) : k >= 97 && k <= 122 ? String.fromCodePoint(l + k - 97) : d && k >= 48 && k <= 57 ? String.fromCodePoint(d + k - 48) : c; }).join('');
const FONTS = { ...Object.fromEntries(Object.entries(RANGES).map(([n, r]) => [n, (t) => mapChars(t, r)])), 'Underline': (t) => [...t].map((c) => c + '̲').join(''), 'Strikethrough': (t) => [...t].map((c) => c + '̶').join('') };

const BIOS = { Founder: ['Building {thing}. Previously {company}. Sharing what I learn.', 'Founder @ {thing}. Helping {audience} {outcome}. DMs open.'], Creator: ['Making {topic} content for {audience}. New posts daily.', '{topic} • {n}+ posts • Newsletter below ↓'], Developer: ['Software engineer. {stack}. Shipping side projects in public.', 'Building dev tools. Writing about {topic}.'], Marketer: ['Growth @ {company}. {n} experiments/yr. Threads on {topic}.', 'I help {audience} get {outcome}. Free playbook ↓'], Investor: ['Investing in {stage} {sector}. Views my own.', 'Backing founders who {trait}. Ex-{company}.'], Writer: ['Writer. {topic}. Essays weekly → link.', 'Words about {topic}, one post at a time.'], Designer: ['Designing {product}. Type nerd. Sharing UI teardowns.', 'Product designer. Making software feel {feeling}.'], Indie: ['Indie hacker. ${mrr} MRR. Building in public.', 'Solo founder of {thing}. Revenue: ${mrr}/mo. Ask me anything about {topic}.'], Coach: ['Helping {audience} {outcome} in {time}. Free guide ↓', '{n} clients coached. Evidence over hype.'], Student: ['Learning {topic} in public. {school} ’{yy}.', 'Student → {goal}. Posting my progress.'] };
const BANNERS = { Founder: ['#0f172a', '#6d8bff'], Creator: ['#3b0764', '#f472b6'], Developer: ['#022c22', '#34d399'], Marketer: ['#431407', '#fb923c'], Investor: ['#111827', '#fbbf24'], Writer: ['#1c1917', '#a8a29e'], Designer: ['#1e1b4b', '#a78bfa'], Indie: ['#052e16', '#84cc16'], Coach: ['#172554', '#38bdf8'], Student: ['#4a044e', '#e879f9'], Minimal: ['#ffffff', '#e5e7eb'], Noir: ['#000000', '#374151'] };
const POSTER_STYLES = ['Midnight', 'Sunset', 'Ocean', 'Forest', 'Neon', 'Paper', 'Mono', 'Candy', 'Slate', 'Aurora', 'Lava', 'Mint', 'Royal', 'Sand', 'Ink', 'Glass'];
const PALETTES = { Midnight: ['#0b1020', '#6d8bff'], Sunset: ['#3b0a45', '#ff7a59'], Ocean: ['#022b3a', '#1fc0d6'], Forest: ['#0b2b1a', '#5be584'], Neon: ['#0a0a0a', '#39ff14'], Paper: ['#faf6ee', '#2b2b2b'], Mono: ['#111', '#eee'], Candy: ['#ffe4f1', '#ff5da2'], Slate: ['#1f2937', '#94a3b8'], Aurora: ['#0d1b2a', '#7cf7c3'], Lava: ['#1a0000', '#ff3b00'], Mint: ['#e8fff5', '#00b37e'], Royal: ['#1b1464', '#ffd700'], Sand: ['#f3e3c3', '#a0522d'], Ink: ['#fff', '#000'], Glass: ['#c9d6ff', '#e2e2e2'] };

const PROMPT_TEMPLATES = [
  ['hook', 'Hook → list', 'I studied [X] for [time].\n\nHere are [N] lessons nobody tells you:\n\n1. \n2. \n3. '], ['hook', 'Contrarian', 'Unpopular opinion:\n\n[Common belief] is wrong.\n\nHere\'s why: '], ['hook', 'Numbers hook', '[N] [things] that took me [time] to learn:\n\n'],
  ['story', 'Story arc', '[Time] ago I [failure].\n\nToday I [result].\n\nThe difference:\n\n1. \n2. \n3. '], ['story', 'Before/After', 'Before: [painful state]\nAfter: [desired state]\n\nWhat changed: [one thing]'], ['story', 'Lesson learned', 'I lost [X] because of [mistake].\n\nDon\'t repeat it:\n\n'],
  ['thread', 'Framework', 'The [Name] framework:\n\n[Step 1] → \n[Step 2] → \n[Step 3] → \n\nSave this.'], ['thread', 'Teardown', 'I tore down [company]\'s [thing].\n\nWhat they do right (and wrong):\n\n1/'], ['thread', 'Playbook', 'How to [outcome] in [time] (step by step):\n\n1/'],
  ['engage', 'Question', '[Provocative question]?\n\nMy answer: '], ['engage', 'This or that', '[Option A] or [Option B]?\n\nI pick [X] because '], ['engage', 'Poll-style', 'Which is harder?\n\nA) \nB) \n\nReply with A or B.'],
  ['announce', 'Launch', 'I just launched [product].\n\nIt helps [audience] [outcome].\n\n[Link]\n\nWhy I built it:'], ['announce', 'Milestone', '[Number] [metric] in [time].\n\nWhat worked:\n\n• \n• \n• \n\nWhat didn\'t: '], ['announce', 'Hiring', 'We\'re hiring a [role].\n\nWhat you\'ll do:\n• \n• \n\nApply: [link]'],
  ['value', 'Checklist', '[Topic] checklist:\n\n☐ \n☐ \n☐ \n☐ \n\nBookmark this.'], ['value', 'Cheat sheet', '[Topic] cheat sheet:\n\n[Term] = [definition]\n[Term] = [definition]\n'], ['value', 'Mistakes', '[N] mistakes I see with [topic]:\n\n1. \n2. \n3. '],
  ['personal', 'Day in life', 'A day building [thing]:\n\n6am: \n9am: \n2pm: \n8pm: '], ['personal', 'Confession', 'Confession: I [embarrassing thing].\n\nHere\'s what it taught me:'], ['personal', 'Gratitude', 'Thank you to [people]. Because of you, [result].'],
  ['sales', 'Case study', 'How [client] got [result] in [time]:\n\nProblem:\nSolution:\nResult:'], ['sales', 'Offer', 'I\'ll [deliver outcome] for [audience] in [time].\n\nDM "[keyword]" to get started.'], ['sales', 'Objection', '"[Common objection]"\n\nHere\'s the truth: '],
  ['curation', 'Tool stack', 'My [topic] stack (and what each costs):\n\n• [Tool]: $\n• [Tool]: $'], ['curation', 'Reading list', '5 books that changed how I think about [topic]:\n\n1. \n2. '], ['curation', 'Follow list', 'Follow these [N] accounts for [topic]:\n\n@ \n@ \n@ '],
  ['trend', 'Trend take', '[Trend] everyone is talking about.\n\nMy take:\n\n1. \n2. '], ['trend', 'Prediction', 'Prediction: by [year], [bold claim].\n\nReasons:\n\n1. \n2. '], ['trend', 'Myth-busting', 'Myth: [common belief]\nReality: [truth]\nProof: [evidence]'],
];

export const TOOLS2 = {
  'Tweet tester': () => { const ta = h('textarea', { placeholder: 'Paste a draft…', style: 'min-height:140px' }); const out = h('div', { style: 'margin-top:12px' }); const media = h('input', { type: 'checkbox', style: 'width:auto' });
    const go = async () => { try { const r = await api('/tools/tweet-tester', { body: { accountId: acct(), text: ta.value, hasMedia: media.checked } });
      out.replaceChildren(h('div', { class: 'split' }, h('div', { class: 'card' }, h('div', { class: 'big' }, r.score), h('div', {}, r.verdict), meter(r.score), h('p', { class: 'mute' }, r.note)),
        h('div', { class: 'card' }, h('h3', {}, 'Predicted vs your median'), h('div', { class: 'row' }, ['likes', 'replies', 'reposts'].map((k) => h('div', { class: 'stat' }, h('small', {}, k + (k === 'reposts' ? ' (low confidence)' : '')), h('b', {}, r.predicted[k]), h('small', {}, 'median ' + r.baseline[k])))))),
        h('div', { class: 'split' }, h('div', { class: 'card' }, h('h3', {}, '👍 Helping'), r.helps.length ? r.helps.map((x) => h('div', {}, '• ' + x)) : 'Nothing notable'), h('div', { class: 'card' }, h('h3', {}, '👎 Hurting'), r.hurts.length ? r.hurts.map((x) => h('div', {}, '• ' + x)) : 'Nothing notable')),
        h('div', { class: 'card' }, h('h3', {}, 'Feed preview'), h('div', { class: 'post' }, h('b', {}, state.accounts.find((a) => a.id === acct())?.name || 'You'), ' ', h('span', { class: 'mute' }, '@' + (state.accounts.find((a) => a.id === acct())?.username || 'you') + ' · now'), '\n' + ta.value))); } catch (e) { toast(e.message, true); } };
    return h('div', {}, ta, h('label', {}, media, ' Has media'), h('div', { style: 'margin-top:8px' }, h('button', { onclick: go }, 'Score it')), out); },

  'Profile analytics': () => usernameTool('Analyze', '/profile', (r, uname) => {
    const chat = h('div', {}), q = h('input', { placeholder: 'Ask about this profile…', onkeydown: async (e) => { if (e.key !== 'Enter') return; chat.append(h('div', { class: 'post' }, '🧑 ' + q.value)); const v = q.value; q.value = ''; try { chat.append(h('div', { class: 'post' }, (await api('/profile/chat', { body: { accountId: acct(), username: uname, question: v } })).result)); } catch (x) { toast(x.message, true); } } });
    return h('div', {}, h('div', { class: 'grid g4' }, [['Followers', fmt(r.user.public_metrics.followers_count)], ['Archetype', r.archetype], ['Health', r.health.score + '/100 · ' + r.health.band], ['Est. per sponsored post', '$' + fmt(r.estimatedEarnings.perSponsoredPost)], ['Median views', fmt(r.metrics.views.median)], ['Avg views', fmt(r.metrics.views.average)], ['Est. account value', '$' + fmt(r.valuation.accountValue)]].map(([k, v]) => h('div', { class: 'stat' }, h('small', {}, k), h('b', { style: 'font-size:18px' }, v)))),
      h('div', { class: 'card', style: 'margin-top:12px' }, h('h3', {}, 'Health breakdown'), r.health.categories.map((c) => h('div', {}, h('div', { class: 'row' }, h('span', { class: 'grow' }, c.name), h('span', {}, `${c.pts}/${c.max}`)), meter(c.pts / c.max * 100))), h('h3', { style: 'margin-top:12px' }, 'Recommendations'), r.health.recommendations.map((x) => h('div', {}, '• ' + x))),
      h('div', { class: 'card' }, h('h3', {}, 'Top posts'), r.topPosts.map((t) => h('div', { class: 'post' }, t.text, h('div', { class: 'mute' }, `${fmt(t.impression_count)} imp · ${t.like_count} ♥ · ${t.retweet_count} ⟲`)))),
      h('div', { class: 'card' }, h('h3', {}, 'Chat with this profile'), chat, q)); }),

  'Profile health audit': () => usernameTool('Audit', '/profile', (r) => h('div', { class: 'card' }, h('div', { class: 'big' }, r.health.score), h('div', {}, r.health.band + (r.health.score > 70 ? ' — solid' : r.health.score >= 50 ? ' — clear opportunities' : ' — significant issues')), meter(r.health.score), r.health.categories.map((c) => h('div', { style: 'margin-top:8px' }, `${c.name}: ${c.pts}/${c.max}`)), h('h3', { style: 'margin-top:12px' }, 'Do next'), r.health.recommendations.map((x) => h('div', {}, '• ' + x)))),

  'Account value calculator': () => usernameTool('Calculate', '/tools/valuation', (v) => h('div', { class: 'card' }, h('div', { class: 'big' }, '$' + fmt(v.accountValue)), h('div', { class: 'mute' }, `Sponsored post ≈ $${fmt(v.sponsoredPostPrice)}`),
    h('table', {}, [['Posts analyzed (max 100)', v.postsAnalyzed], ['Average views / post', fmt(v.avgViews)], ['Engagement rate', v.engagementRate + '% (baseline 2%)'], ['CPM', '$' + v.cpm], ['Engagement multiplier (0.5x–2x)', v.multiplier + 'x'], ['Sponsored posts × months', `${v.postsPerMonth} × ${v.months}`]].map(([a, b]) => h('tr', {}, h('td', {}, a), h('td', {}, b)))), h('p', { class: 'mute' }, v.formula), h('p', { class: 'mute' }, v.disclaimer))),

  'Metrics calculator': () => usernameTool('Calculate', '/tools/metrics', (m) => h('div', { class: 'grid g4' }, [['Posts', m.posts], ['Views total', fmt(m.views.total)], ['Views avg', fmt(m.views.average)], ['Views median', fmt(m.views.median)], ['Engagement total', fmt(m.engagement.total)], ['Engagement avg', m.engagement.average], ['Engagement median', m.engagement.median]].map(([k, v]) => h('div', { class: 'stat' }, h('small', {}, k), h('b', {}, v))))),

  'Live follower counter': () => { const u = h('input', { placeholder: '@username', style: 'max-width:240px' }); const out = h('div', { style: 'margin-top:14px' }); let timer;
    const tick = async () => { try { const c = await api(`/tools/counter?account=${acct()}&username=${encodeURIComponent(u.value.replace(/^@/, ''))}`); out.replaceChildren(h('div', { class: 'big' }, c.followers_count.toLocaleString()), h('div', { class: 'mute' }, `@${c.username} · following ${c.following_count.toLocaleString()} · updated ${new Date(c.at).toLocaleTimeString()} (every 15s)`)); } catch (e) { out.textContent = e.message; clearInterval(timer); } };
    return h('div', {}, h('div', { class: 'row' }, u, h('button', { onclick: () => { clearInterval(timer); tick(); timer = setInterval(() => (document.contains(out) ? tick() : clearInterval(timer)), 15000); } }, 'Track')), out); },

  'Roast': () => { const u = h('input', { placeholder: '@username', style: 'max-width:240px' }); const out = h('pre', {}); return h('div', {}, h('div', { class: 'row' }, u, h('button', { onclick: async (e) => { e.target.disabled = true; out.textContent = 'Roasting…'; try { out.textContent = (await api('/ai-tools/roast', { body: { accountId: acct(), username: u.value } })).result; } catch (x) { out.textContent = x.message; } e.target.disabled = false; } }, 'Roast')), out); },

  'Doomscroll filter': () => { const u = h('input', { placeholder: '@username', style: 'max-width:240px' }), niche = h('input', { placeholder: 'Your niche', style: 'max-width:240px' }), out = h('div', {}); return h('div', {}, h('div', { class: 'row' }, u, niche, h('button', { onclick: async (e) => { e.target.disabled = true; out.textContent = 'Reading…'; try { const r = (await api('/ai-tools/doomscroll', { body: { accountId: acct(), username: u.value, niche: niche.value } })).result; out.replaceChildren(...r.map((x) => h('div', { class: 'post' }, h('span', { class: 'tag ' + (x.verdict === 'Read' ? 'posted' : x.verdict === 'Pass' ? 'failed' : 'draft') }, x.verdict), ' ', x.text, h('div', { class: 'mute' }, x.why)))); } catch (x) { out.textContent = x.message; } e.target.disabled = false; } }, 'Filter')), out); },

  'Fact-check': () => { const ta = h('textarea', { placeholder: 'Paste a post or claim…' }); const out = h('pre', {}); return h('div', {}, ta, h('button', { onclick: async () => { out.textContent = 'Checking…'; try { out.textContent = (await api('/ai-tools/factcheck', { body: { text: ta.value } })).result; } catch (e) { out.textContent = e.message; } } }, 'Fact-check'), out); },

  'AI Shield': () => { const ta = h('textarea', { placeholder: 'Paste a reply…' }); const out = h('div', { style: 'margin-top:10px' }); return h('div', {}, ta, h('button', { onclick: async () => { const s = await api('/shield', { body: { text: ta.value, deep: true } }); out.replaceChildren(h('div', { class: 'big' }, s.score), shieldTag(s), s.reasons.map((r) => h('div', {}, '• ' + r)), s.deep && h('div', { class: 'mute' }, 'AI second opinion: ' + s.deep.score + ' — ' + s.deep.reason)); } }, 'Check'), out); },

  'AI writers': () => { const kind = h('select', {}, [['tweets', 'Tweets (3)'], ['text', 'Text'], ['paragraph', 'Paragraph'], ['content', 'Content'], ['story', 'Story'], ['writer', 'General writer']].map(([v, l]) => h('option', { value: v }, l))), len = h('select', {}, ['short', 'medium', 'long'].map((x) => h('option', {}, x))), t = h('textarea', { placeholder: 'Topic…', style: 'min-height:80px' }), out = h('div', {});
    return h('div', {}, h('div', { class: 'row' }, kind, len), t, h('button', { onclick: async (e) => { e.target.disabled = true; out.textContent = 'Writing…'; try { const r = (await api('/ai-tools/write', { body: { kind: kind.value, length: len.value, topic: t.value } })).result; out.replaceChildren(...(Array.isArray(r) ? r : [r]).map((x) => h('div', { class: 'post' }, x, h('div', {}, h('button', { class: 'ghost', onclick: () => copy(x) }, 'Copy'))))); } catch (x) { out.textContent = x.message; } e.target.disabled = false; } }, 'Generate'), out); },

  'Fonts generator': () => { const ta = h('textarea', { placeholder: 'Type text…' }); const out = h('div', {}); const up = () => out.replaceChildren(...Object.entries(FONTS).map(([n, f]) => h('div', { class: 'post' }, h('div', { class: 'mute' }, n), f(ta.value || 'Sample text'), h('div', {}, h('button', { class: 'ghost', onclick: () => copy(f(ta.value || 'Sample text')) }, 'Copy'))))); ta.addEventListener('input', up); up(); return h('div', {}, ta, out); },

  'Bio templates': () => { const sel = h('select', {}, Object.keys(BIOS).map((k) => h('option', {}, k))); const out = h('div', {}); const up = () => out.replaceChildren(...BIOS[sel.value].map((b) => h('div', { class: 'post' }, b, h('div', {}, h('button', { class: 'ghost', onclick: () => copy(b) }, 'Copy'))))); sel.addEventListener('change', up); up(); return h('div', {}, sel, out); },

  'Post templates (library)': async () => { const custom = await api('/templates'); const cats = [...new Set(PROMPT_TEMPLATES.map((t) => t[0]))]; const cat = h('select', {}, h('option', { value: '' }, 'All categories'), cats.map((c) => h('option', {}, c))); const list = h('div', {});
    const draw = () => list.replaceChildren(...[...custom.map((c) => ['custom', c.title, c.body, c.id]), ...PROMPT_TEMPLATES].filter((t) => !cat.value || t[0] === cat.value).map(([c, n, b, id]) => h('div', { class: 'post' }, h('span', { class: 'tag' }, c), ' ', h('b', {}, n), '\n' + b, h('div', { class: 'row', style: 'margin-top:6px' }, h('button', { class: 'ghost', onclick: () => copy(b) }, 'Copy'), h('button', { class: 'ghost', onclick: () => { sessionStorage.setItem('draft', JSON.stringify({ text: b })); location.hash = '#/compose'; } }, 'Use'), id && h('button', { class: 'danger', onclick: async () => { await api('/templates/' + id, { method: 'DELETE' }); location.reload(); } }, 'Delete')))));
    cat.addEventListener('change', draw); draw(); const tt = h('input', { placeholder: 'Template title' }), tb = h('textarea', { placeholder: 'Template body' });
    return h('div', {}, h('p', { class: 'mute' }, `${PROMPT_TEMPLATES.length} built-in + your own.`), cat, list, h('div', { class: 'card' }, h('h3', {}, 'Save your own'), tt, tb, h('button', { onclick: async () => { await api('/templates', { body: { title: tt.value, body: tb.value } }); location.reload(); } }, 'Save'))); },

  'Graph → poster': async () => { const a = await api(`/analytics?account=${acct()}&days=30`); const style = h('select', {}, POSTER_STYLES.map((s) => h('option', {}, s))), metric = h('select', {}, ['impressions', 'engagements', 'posts'].map((s) => h('option', {}, s))), title = h('input', { value: 'My last 30 days on X' }); const cv = h('canvas', { width: 1200, height: 675 });
    const draw = () => { const [bg, fg] = PALETTES[style.value]; const c = cv.getContext('2d'); c.fillStyle = bg; c.fillRect(0, 0, 1200, 675); c.fillStyle = fg; c.font = 'bold 54px system-ui'; c.fillText(title.value, 70, 110); c.globalAlpha = .7; c.font = '28px system-ui'; c.fillText(`${fmt(a.impressions)} impressions · ${a.engagementRate}% engagement · ${a.followersGained >= 0 ? '+' : ''}${a.followersGained} followers`, 70, 160); c.globalAlpha = 1;
      const d = a.daily; const max = Math.max(1, ...d.map((x) => x[metric.value])); const w = 1060 / Math.max(1, d.length); d.forEach((x, i) => { const hh = (x[metric.value] / max) * 380; c.fillStyle = fg; c.globalAlpha = .85; c.beginPath(); c.roundRect(70 + i * w + 2, 600 - hh, Math.max(3, w - 4), hh, 4); c.fill(); }); c.globalAlpha = 1; };
    [style, metric, title].forEach((e) => e.addEventListener('input', draw)); setTimeout(draw, 0); return h('div', {}, h('div', { class: 'row' }, style, metric, title), cv, h('div', {}, h('button', { onclick: () => h('a', { download: 'poster.png', href: cv.toDataURL() }).click() }, 'Download PNG'))); },

  'Twitter trends': () => { const woe = h('select', {}, [[1, 'Worldwide'], [23424977, 'United States'], [23424975, 'United Kingdom'], [23424748, 'Australia'], [23424775, 'Canada'], [23424829, 'Germany'], [23424819, 'France'], [23424856, 'Japan'], [23424848, 'India'], [23424768, 'Brazil'], [23424900, 'Mexico'], [23424950, 'Spain']].map(([v, l]) => h('option', { value: v }, l))); const out = h('div', { style: 'margin-top:10px' });
    const load = async () => { try { const r = await api(`/trends?account=${acct()}&woeid=${woe.value}`); out.replaceChildren(...(r.data || []).map((t, i) => h('div', { class: 'post' }, `${i + 1}. ${t.trend_name}`, t.post_count ? h('span', { class: 'mute' }, ` · ${fmt(t.post_count)} posts`) : '', h('div', {}, h('button', { class: 'ghost', onclick: async () => { try { const p = (await api('/ai/trend', { body: { trend: t.trend_name } })).result; sessionStorage.setItem('draft', JSON.stringify({ text: p[0] })); location.hash = '#/compose'; } catch (e) { toast(e.message, true); } } }, '✨ Post about this'))))); } catch (e) { out.textContent = e.message; } };
    woe.addEventListener('change', load); return h('div', {}, woe, h('span', { class: 'mute' }, ' refresh every 15 min (X limits)'), out, (load(), '')); },

  'Best tweets': async () => { const rows = await api('/viral?sort=likes'); return h('div', {}, h('p', { class: 'mute' }, 'Top posts from your viral library (add more via Inspiration).'), rows.slice(0, 50).map((v, i) => h('div', { class: 'post' }, `${i + 1}. ${v.text}`, h('div', { class: 'mute' }, `@${v.author} · ${fmt(v.likes)} ♥`)))); },

  'Blank tweet template': () => { const c = document.createElement('canvas'); c.width = 1200; c.height = 675; const dark = h('select', {}, h('option', { value: 'light' }, 'Light'), h('option', { value: 'dark' }, 'Dark')); const draw = () => { const x = c.getContext('2d'); x.fillStyle = dark.value === 'dark' ? '#0f1116' : '#fff'; x.fillRect(0, 0, 1200, 675); x.strokeStyle = '#8b98a5'; x.strokeRect(60, 60, 1080, 555); x.fillStyle = '#8b98a5'; x.font = '30px system-ui'; x.fillText('Name  @handle', 140, 130); x.fillText('Your text here…', 100, 220); }; dark.addEventListener('input', draw); draw(); return h('div', {}, dark, h('div', {}, c), h('button', { onclick: () => h('a', { download: 'blank.png', href: c.toDataURL() }).click() }, 'Download')); },
};
export { usernameTool, BANNERS };
